<?php
// auto-generated by sfAdvancedAdmin
// date: 2008/01/10 11:37:49
?>
    <td><?php echo $sesion->getIdSesion() ?></td>
      <td><?php echo link_to($sesion->getNombreUsuario(), 'usuarios/show?id_usuario='.$sesion->getIdUsuario()) ?></td>
    <!--  <td><?php echo link_to($sesion->getSesion(),'logUsuarios/list?id_sesion='.$sesion->getIdSesion()) ?></td>-->
      <td><?php echo $sesion->getPrimerSuceso()?></td>
      <td><?php echo $sesion->getUltimoSuceso()?></td>
      <td><?php echo $sesion->getIP() ?></td>
      <td><?php echo $sesion->countSesionLogs() ?></td>
  