<?php
// auto-generated by sfPropelAdmin
// date: 2007/08/31 08:58:25
?>
    <td><?php echo link_to($grupo->getIdGrupo() ? $grupo->getIdGrupo() : '-', 'grupos/edit?id_grupo='.$grupo->getIdGrupo()) ?></td>
    <td><?php echo $grupo->getNombre() ?></td>
  