<?php
// auto-generated by sfAdvancedAdmin
// date: 2008/01/10 11:37:55
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Sesiones'), 'sesiones/list', array (
  'class' => 'sf_admin_action_list',
)) ?></li>
</ul>
