<?php

/**
 * Base class that represents a row from the 'formulario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Oct 27 21:17:36 2010
 *
 * @package    lib.model.om
 */
abstract class BaseFormulario extends BaseObject  implements Persistent {


  const PEER = 'FormularioPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FormularioPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_formulario field.
	 * @var        int
	 */
	protected $id_formulario;

	/**
	 * The value for the id_tabla field.
	 * @var        int
	 */
	protected $id_tabla;

	/**
	 * The value for the id_usuario_creador field.
	 * @var        int
	 */
	protected $id_usuario_creador;

	/**
	 * The value for the id_usuario field.
	 * @var        int
	 */
	protected $id_usuario;

	/**
	 * The value for the fecha field.
	 * @var        string
	 */
	protected $fecha;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Tabla
	 */
	protected $aTabla;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByIdUsuario;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByIdUsuarioCreador;

	/**
	 * @var        array Item[] Collection to store aggregation of Item objects.
	 */
	protected $collItems;

	/**
	 * @var        Criteria The criteria used to select the current contents of collItems.
	 */
	private $lastItemCriteria = null;

	/**
	 * @var        array Notificaciones[] Collection to store aggregation of Notificaciones objects.
	 */
	protected $collNotificacioness;

	/**
	 * @var        Criteria The criteria used to select the current contents of collNotificacioness.
	 */
	private $lastNotificacionesCriteria = null;

	/**
	 * @var        array Tarea[] Collection to store aggregation of Tarea objects.
	 */
	protected $collTareas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTareas.
	 */
	private $lastTareaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseFormulario object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id_formulario] column value.
	 * 
	 * @return     int
	 */
	public function getIdFormulario()
	{
		return $this->id_formulario;
	}

	/**
	 * Get the [id_tabla] column value.
	 * 
	 * @return     int
	 */
	public function getIdTabla()
	{
		return $this->id_tabla;
	}

	/**
	 * Get the [id_usuario_creador] column value.
	 * 
	 * @return     int
	 */
	public function getIdUsuarioCreador()
	{
		return $this->id_usuario_creador;
	}

	/**
	 * Get the [id_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getIdUsuario()
	{
		return $this->id_usuario;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFecha($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha === null) {
			return null;
		}


		if ($this->fecha === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id_formulario] column.
	 * 
	 * @param      int $v new value
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setIdFormulario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_formulario !== $v) {
			$this->id_formulario = $v;
			$this->modifiedColumns[] = FormularioPeer::ID_FORMULARIO;
		}

		return $this;
	} // setIdFormulario()

	/**
	 * Set the value of [id_tabla] column.
	 * 
	 * @param      int $v new value
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setIdTabla($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tabla !== $v) {
			$this->id_tabla = $v;
			$this->modifiedColumns[] = FormularioPeer::ID_TABLA;
		}

		if ($this->aTabla !== null && $this->aTabla->getIdTabla() !== $v) {
			$this->aTabla = null;
		}

		return $this;
	} // setIdTabla()

	/**
	 * Set the value of [id_usuario_creador] column.
	 * 
	 * @param      int $v new value
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setIdUsuarioCreador($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_usuario_creador !== $v) {
			$this->id_usuario_creador = $v;
			$this->modifiedColumns[] = FormularioPeer::ID_USUARIO_CREADOR;
		}

		if ($this->aUsuarioRelatedByIdUsuarioCreador !== null && $this->aUsuarioRelatedByIdUsuarioCreador->getIdUsuario() !== $v) {
			$this->aUsuarioRelatedByIdUsuarioCreador = null;
		}

		return $this;
	} // setIdUsuarioCreador()

	/**
	 * Set the value of [id_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setIdUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_usuario !== $v) {
			$this->id_usuario = $v;
			$this->modifiedColumns[] = FormularioPeer::ID_USUARIO;
		}

		if ($this->aUsuarioRelatedByIdUsuario !== null && $this->aUsuarioRelatedByIdUsuario->getIdUsuario() !== $v) {
			$this->aUsuarioRelatedByIdUsuario = null;
		}

		return $this;
	} // setIdUsuario()

	/**
	 * Sets the value of [fecha] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setFecha($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha !== null && $tmpDt = new DateTime($this->fecha)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FormularioPeer::FECHA;
			}
		} // if either are not null

		return $this;
	} // setFecha()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FormularioPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Formulario The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FormularioPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_formulario = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_tabla = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->id_usuario_creador = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->id_usuario = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->fecha = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->created_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->updated_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = FormularioPeer::NUM_COLUMNS - FormularioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Formulario object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTabla !== null && $this->id_tabla !== $this->aTabla->getIdTabla()) {
			$this->aTabla = null;
		}
		if ($this->aUsuarioRelatedByIdUsuarioCreador !== null && $this->id_usuario_creador !== $this->aUsuarioRelatedByIdUsuarioCreador->getIdUsuario()) {
			$this->aUsuarioRelatedByIdUsuarioCreador = null;
		}
		if ($this->aUsuarioRelatedByIdUsuario !== null && $this->id_usuario !== $this->aUsuarioRelatedByIdUsuario->getIdUsuario()) {
			$this->aUsuarioRelatedByIdUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FormularioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FormularioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTabla = null;
			$this->aUsuarioRelatedByIdUsuario = null;
			$this->aUsuarioRelatedByIdUsuarioCreador = null;
			$this->collItems = null;
			$this->lastItemCriteria = null;

			$this->collNotificacioness = null;
			$this->lastNotificacionesCriteria = null;

			$this->collTareas = null;
			$this->lastTareaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFormulario:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FormularioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			FormularioPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseFormulario:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFormulario:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(FormularioPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(FormularioPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FormularioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseFormulario:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			FormularioPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTabla !== null) {
				if ($this->aTabla->isModified() || $this->aTabla->isNew()) {
					$affectedRows += $this->aTabla->save($con);
				}
				$this->setTabla($this->aTabla);
			}

			if ($this->aUsuarioRelatedByIdUsuario !== null) {
				if ($this->aUsuarioRelatedByIdUsuario->isModified() || $this->aUsuarioRelatedByIdUsuario->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByIdUsuario->save($con);
				}
				$this->setUsuarioRelatedByIdUsuario($this->aUsuarioRelatedByIdUsuario);
			}

			if ($this->aUsuarioRelatedByIdUsuarioCreador !== null) {
				if ($this->aUsuarioRelatedByIdUsuarioCreador->isModified() || $this->aUsuarioRelatedByIdUsuarioCreador->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByIdUsuarioCreador->save($con);
				}
				$this->setUsuarioRelatedByIdUsuarioCreador($this->aUsuarioRelatedByIdUsuarioCreador);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FormularioPeer::ID_FORMULARIO;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FormularioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdFormulario($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FormularioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collItems !== null) {
				foreach ($this->collItems as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collNotificacioness !== null) {
				foreach ($this->collNotificacioness as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTareas !== null) {
				foreach ($this->collTareas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTabla !== null) {
				if (!$this->aTabla->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTabla->getValidationFailures());
				}
			}

			if ($this->aUsuarioRelatedByIdUsuario !== null) {
				if (!$this->aUsuarioRelatedByIdUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByIdUsuario->getValidationFailures());
				}
			}

			if ($this->aUsuarioRelatedByIdUsuarioCreador !== null) {
				if (!$this->aUsuarioRelatedByIdUsuarioCreador->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByIdUsuarioCreador->getValidationFailures());
				}
			}


			if (($retval = FormularioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collItems !== null) {
					foreach ($this->collItems as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collNotificacioness !== null) {
					foreach ($this->collNotificacioness as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTareas !== null) {
					foreach ($this->collTareas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FormularioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdFormulario();
				break;
			case 1:
				return $this->getIdTabla();
				break;
			case 2:
				return $this->getIdUsuarioCreador();
				break;
			case 3:
				return $this->getIdUsuario();
				break;
			case 4:
				return $this->getFecha();
				break;
			case 5:
				return $this->getCreatedAt();
				break;
			case 6:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FormularioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdFormulario(),
			$keys[1] => $this->getIdTabla(),
			$keys[2] => $this->getIdUsuarioCreador(),
			$keys[3] => $this->getIdUsuario(),
			$keys[4] => $this->getFecha(),
			$keys[5] => $this->getCreatedAt(),
			$keys[6] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FormularioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdFormulario($value);
				break;
			case 1:
				$this->setIdTabla($value);
				break;
			case 2:
				$this->setIdUsuarioCreador($value);
				break;
			case 3:
				$this->setIdUsuario($value);
				break;
			case 4:
				$this->setFecha($value);
				break;
			case 5:
				$this->setCreatedAt($value);
				break;
			case 6:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FormularioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdFormulario($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdTabla($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdUsuarioCreador($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setIdUsuario($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFecha($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCreatedAt($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUpdatedAt($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FormularioPeer::DATABASE_NAME);

		if ($this->isColumnModified(FormularioPeer::ID_FORMULARIO)) $criteria->add(FormularioPeer::ID_FORMULARIO, $this->id_formulario);
		if ($this->isColumnModified(FormularioPeer::ID_TABLA)) $criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);
		if ($this->isColumnModified(FormularioPeer::ID_USUARIO_CREADOR)) $criteria->add(FormularioPeer::ID_USUARIO_CREADOR, $this->id_usuario_creador);
		if ($this->isColumnModified(FormularioPeer::ID_USUARIO)) $criteria->add(FormularioPeer::ID_USUARIO, $this->id_usuario);
		if ($this->isColumnModified(FormularioPeer::FECHA)) $criteria->add(FormularioPeer::FECHA, $this->fecha);
		if ($this->isColumnModified(FormularioPeer::CREATED_AT)) $criteria->add(FormularioPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(FormularioPeer::UPDATED_AT)) $criteria->add(FormularioPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FormularioPeer::DATABASE_NAME);

		$criteria->add(FormularioPeer::ID_FORMULARIO, $this->id_formulario);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdFormulario();
	}

	/**
	 * Generic method to set the primary key (id_formulario column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdFormulario($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Formulario (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdTabla($this->id_tabla);

		$copyObj->setIdUsuarioCreador($this->id_usuario_creador);

		$copyObj->setIdUsuario($this->id_usuario);

		$copyObj->setFecha($this->fecha);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getItems() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addItem($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getNotificacioness() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addNotificaciones($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTareas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTarea($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdFormulario(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Formulario Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FormularioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FormularioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Tabla object.
	 *
	 * @param      Tabla $v
	 * @return     Formulario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTabla(Tabla $v = null)
	{
		if ($v === null) {
			$this->setIdTabla(NULL);
		} else {
			$this->setIdTabla($v->getIdTabla());
		}

		$this->aTabla = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tabla object, it will not be re-added.
		if ($v !== null) {
			$v->addFormulario($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tabla object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tabla The associated Tabla object.
	 * @throws     PropelException
	 */
	public function getTabla(PropelPDO $con = null)
	{
		if ($this->aTabla === null && ($this->id_tabla !== null)) {
			$c = new Criteria(TablaPeer::DATABASE_NAME);
			$c->add(TablaPeer::ID_TABLA, $this->id_tabla);
			$this->aTabla = TablaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTabla->addFormularios($this);
			 */
		}
		return $this->aTabla;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Formulario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByIdUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setIdUsuario(NULL);
		} else {
			$this->setIdUsuario($v->getIdUsuario());
		}

		$this->aUsuarioRelatedByIdUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addFormularioRelatedByIdUsuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByIdUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByIdUsuario === null && ($this->id_usuario !== null)) {
			$c = new Criteria(UsuarioPeer::DATABASE_NAME);
			$c->add(UsuarioPeer::ID_USUARIO, $this->id_usuario);
			$this->aUsuarioRelatedByIdUsuario = UsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByIdUsuario->addFormulariosRelatedByIdUsuario($this);
			 */
		}
		return $this->aUsuarioRelatedByIdUsuario;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Formulario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByIdUsuarioCreador(Usuario $v = null)
	{
		if ($v === null) {
			$this->setIdUsuarioCreador(NULL);
		} else {
			$this->setIdUsuarioCreador($v->getIdUsuario());
		}

		$this->aUsuarioRelatedByIdUsuarioCreador = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addFormularioRelatedByIdUsuarioCreador($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByIdUsuarioCreador(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByIdUsuarioCreador === null && ($this->id_usuario_creador !== null)) {
			$c = new Criteria(UsuarioPeer::DATABASE_NAME);
			$c->add(UsuarioPeer::ID_USUARIO, $this->id_usuario_creador);
			$this->aUsuarioRelatedByIdUsuarioCreador = UsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByIdUsuarioCreador->addFormulariosRelatedByIdUsuarioCreador($this);
			 */
		}
		return $this->aUsuarioRelatedByIdUsuarioCreador;
	}

	/**
	 * Clears out the collItems collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addItems()
	 */
	public function clearItems()
	{
		$this->collItems = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collItems collection (array).
	 *
	 * By default this just sets the collItems collection to an empty array (like clearcollItems());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initItems()
	{
		$this->collItems = array();
	}

	/**
	 * Gets an array of Item objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Formulario has previously been saved, it will retrieve
	 * related Items from storage. If this Formulario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Item[]
	 * @throws     PropelException
	 */
	public function getItems($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItems === null) {
			if ($this->isNew()) {
			   $this->collItems = array();
			} else {

				$criteria->add(ItemPeer::ID_FORMULARIO, $this->id_formulario);

				ItemPeer::addSelectColumns($criteria);
				$this->collItems = ItemPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ItemPeer::ID_FORMULARIO, $this->id_formulario);

				ItemPeer::addSelectColumns($criteria);
				if (!isset($this->lastItemCriteria) || !$this->lastItemCriteria->equals($criteria)) {
					$this->collItems = ItemPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastItemCriteria = $criteria;
		return $this->collItems;
	}

	/**
	 * Returns the number of related Item objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Item objects.
	 * @throws     PropelException
	 */
	public function countItems(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collItems === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ItemPeer::ID_FORMULARIO, $this->id_formulario);

				$count = ItemPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ItemPeer::ID_FORMULARIO, $this->id_formulario);

				if (!isset($this->lastItemCriteria) || !$this->lastItemCriteria->equals($criteria)) {
					$count = ItemPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collItems);
				}
			} else {
				$count = count($this->collItems);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Item object to this object
	 * through the Item foreign key attribute.
	 *
	 * @param      Item $l Item
	 * @return     void
	 * @throws     PropelException
	 */
	public function addItem(Item $l)
	{
		if ($this->collItems === null) {
			$this->initItems();
		}
		if (!in_array($l, $this->collItems, true)) { // only add it if the **same** object is not already associated
			array_push($this->collItems, $l);
			$l->setFormulario($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Formulario is new, it will return
	 * an empty collection; or if this Formulario has previously
	 * been saved, it will retrieve related Items from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Formulario.
	 */
	public function getItemsJoinItemBase($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItems === null) {
			if ($this->isNew()) {
				$this->collItems = array();
			} else {

				$criteria->add(ItemPeer::ID_FORMULARIO, $this->id_formulario);

				$this->collItems = ItemPeer::doSelectJoinItemBase($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ItemPeer::ID_FORMULARIO, $this->id_formulario);

			if (!isset($this->lastItemCriteria) || !$this->lastItemCriteria->equals($criteria)) {
				$this->collItems = ItemPeer::doSelectJoinItemBase($criteria, $con, $join_behavior);
			}
		}
		$this->lastItemCriteria = $criteria;

		return $this->collItems;
	}

	/**
	 * Clears out the collNotificacioness collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addNotificacioness()
	 */
	public function clearNotificacioness()
	{
		$this->collNotificacioness = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collNotificacioness collection (array).
	 *
	 * By default this just sets the collNotificacioness collection to an empty array (like clearcollNotificacioness());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initNotificacioness()
	{
		$this->collNotificacioness = array();
	}

	/**
	 * Gets an array of Notificaciones objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Formulario has previously been saved, it will retrieve
	 * related Notificacioness from storage. If this Formulario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Notificaciones[]
	 * @throws     PropelException
	 */
	public function getNotificacioness($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collNotificacioness === null) {
			if ($this->isNew()) {
			   $this->collNotificacioness = array();
			} else {

				$criteria->add(NotificacionesPeer::ID_FICHERO, $this->id_formulario);

				NotificacionesPeer::addSelectColumns($criteria);
				$this->collNotificacioness = NotificacionesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(NotificacionesPeer::ID_FICHERO, $this->id_formulario);

				NotificacionesPeer::addSelectColumns($criteria);
				if (!isset($this->lastNotificacionesCriteria) || !$this->lastNotificacionesCriteria->equals($criteria)) {
					$this->collNotificacioness = NotificacionesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastNotificacionesCriteria = $criteria;
		return $this->collNotificacioness;
	}

	/**
	 * Returns the number of related Notificaciones objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Notificaciones objects.
	 * @throws     PropelException
	 */
	public function countNotificacioness(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collNotificacioness === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(NotificacionesPeer::ID_FICHERO, $this->id_formulario);

				$count = NotificacionesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(NotificacionesPeer::ID_FICHERO, $this->id_formulario);

				if (!isset($this->lastNotificacionesCriteria) || !$this->lastNotificacionesCriteria->equals($criteria)) {
					$count = NotificacionesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collNotificacioness);
				}
			} else {
				$count = count($this->collNotificacioness);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Notificaciones object to this object
	 * through the Notificaciones foreign key attribute.
	 *
	 * @param      Notificaciones $l Notificaciones
	 * @return     void
	 * @throws     PropelException
	 */
	public function addNotificaciones(Notificaciones $l)
	{
		if ($this->collNotificacioness === null) {
			$this->initNotificacioness();
		}
		if (!in_array($l, $this->collNotificacioness, true)) { // only add it if the **same** object is not already associated
			array_push($this->collNotificacioness, $l);
			$l->setFormulario($this);
		}
	}

	/**
	 * Clears out the collTareas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTareas()
	 */
	public function clearTareas()
	{
		$this->collTareas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTareas collection (array).
	 *
	 * By default this just sets the collTareas collection to an empty array (like clearcollTareas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTareas()
	{
		$this->collTareas = array();
	}

	/**
	 * Gets an array of Tarea objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Formulario has previously been saved, it will retrieve
	 * related Tareas from storage. If this Formulario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tarea[]
	 * @throws     PropelException
	 */
	public function getTareas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTareas === null) {
			if ($this->isNew()) {
			   $this->collTareas = array();
			} else {

				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				TareaPeer::addSelectColumns($criteria);
				$this->collTareas = TareaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				TareaPeer::addSelectColumns($criteria);
				if (!isset($this->lastTareaCriteria) || !$this->lastTareaCriteria->equals($criteria)) {
					$this->collTareas = TareaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTareaCriteria = $criteria;
		return $this->collTareas;
	}

	/**
	 * Returns the number of related Tarea objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tarea objects.
	 * @throws     PropelException
	 */
	public function countTareas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTareas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				$count = TareaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				if (!isset($this->lastTareaCriteria) || !$this->lastTareaCriteria->equals($criteria)) {
					$count = TareaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTareas);
				}
			} else {
				$count = count($this->collTareas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tarea object to this object
	 * through the Tarea foreign key attribute.
	 *
	 * @param      Tarea $l Tarea
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTarea(Tarea $l)
	{
		if ($this->collTareas === null) {
			$this->initTareas();
		}
		if (!in_array($l, $this->collTareas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTareas, $l);
			$l->setFormulario($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Formulario is new, it will return
	 * an empty collection; or if this Formulario has previously
	 * been saved, it will retrieve related Tareas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Formulario.
	 */
	public function getTareasJoinCampo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTareas === null) {
			if ($this->isNew()) {
				$this->collTareas = array();
			} else {

				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				$this->collTareas = TareaPeer::doSelectJoinCampo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

			if (!isset($this->lastTareaCriteria) || !$this->lastTareaCriteria->equals($criteria)) {
				$this->collTareas = TareaPeer::doSelectJoinCampo($criteria, $con, $join_behavior);
			}
		}
		$this->lastTareaCriteria = $criteria;

		return $this->collTareas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Formulario is new, it will return
	 * an empty collection; or if this Formulario has previously
	 * been saved, it will retrieve related Tareas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Formulario.
	 */
	public function getTareasJoinUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTareas === null) {
			if ($this->isNew()) {
				$this->collTareas = array();
			} else {

				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				$this->collTareas = TareaPeer::doSelectJoinUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

			if (!isset($this->lastTareaCriteria) || !$this->lastTareaCriteria->equals($criteria)) {
				$this->collTareas = TareaPeer::doSelectJoinUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastTareaCriteria = $criteria;

		return $this->collTareas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Formulario is new, it will return
	 * an empty collection; or if this Formulario has previously
	 * been saved, it will retrieve related Tareas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Formulario.
	 */
	public function getTareasJoinParametro($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTareas === null) {
			if ($this->isNew()) {
				$this->collTareas = array();
			} else {

				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				$this->collTareas = TareaPeer::doSelectJoinParametro($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

			if (!isset($this->lastTareaCriteria) || !$this->lastTareaCriteria->equals($criteria)) {
				$this->collTareas = TareaPeer::doSelectJoinParametro($criteria, $con, $join_behavior);
			}
		}
		$this->lastTareaCriteria = $criteria;

		return $this->collTareas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Formulario is new, it will return
	 * an empty collection; or if this Formulario has previously
	 * been saved, it will retrieve related Tareas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Formulario.
	 */
	public function getTareasJoinEmpresa($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FormularioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTareas === null) {
			if ($this->isNew()) {
				$this->collTareas = array();
			} else {

				$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

				$this->collTareas = TareaPeer::doSelectJoinEmpresa($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TareaPeer::ID_FORMULARIO, $this->id_formulario);

			if (!isset($this->lastTareaCriteria) || !$this->lastTareaCriteria->equals($criteria)) {
				$this->collTareas = TareaPeer::doSelectJoinEmpresa($criteria, $con, $join_behavior);
			}
		}
		$this->lastTareaCriteria = $criteria;

		return $this->collTareas;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collItems) {
				foreach ((array) $this->collItems as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collNotificacioness) {
				foreach ((array) $this->collNotificacioness as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTareas) {
				foreach ((array) $this->collTareas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collItems = null;
		$this->collNotificacioness = null;
		$this->collTareas = null;
			$this->aTabla = null;
			$this->aUsuarioRelatedByIdUsuario = null;
			$this->aUsuarioRelatedByIdUsuarioCreador = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseFormulario:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseFormulario::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseFormulario
