<?php

/**
 * Base class that represents a row from the 'tabla' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Oct 27 21:17:36 2010
 *
 * @package    lib.model.om
 */
abstract class BaseTabla extends BaseObject  implements Persistent {


  const PEER = 'TablaPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TablaPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_tabla field.
	 * @var        int
	 */
	protected $id_tabla;

	/**
	 * The value for the id_usuario field.
	 * @var        int
	 */
	protected $id_usuario;

	/**
	 * The value for the id_empresa field.
	 * @var        int
	 */
	protected $id_empresa;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the imagen field.
	 * @var        string
	 */
	protected $imagen;

	/**
	 * The value for the mostrar_en_lista field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $mostrar_en_lista;

	/**
	 * The value for the orden field.
	 * @var        int
	 */
	protected $orden;

	/**
	 * The value for the es_ficheros field.
	 * @var        boolean
	 */
	protected $es_ficheros;

	/**
	 * The value for the id_categoria field.
	 * @var        int
	 */
	protected $id_categoria;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the borrado field.
	 * @var        boolean
	 */
	protected $borrado;

	/**
	 * @var        Empresa
	 */
	protected $aEmpresa;

	/**
	 * @var        Usuario
	 */
	protected $aUsuario;

	/**
	 * @var        Parametro
	 */
	protected $aParametro;

	/**
	 * @var        array Alcance[] Collection to store aggregation of Alcance objects.
	 */
	protected $collAlcances;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAlcances.
	 */
	private $lastAlcanceCriteria = null;

	/**
	 * @var        array RelCampoTabla[] Collection to store aggregation of RelCampoTabla objects.
	 */
	protected $collRelCampoTablas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRelCampoTablas.
	 */
	private $lastRelCampoTablaCriteria = null;

	/**
	 * @var        array Formulario[] Collection to store aggregation of Formulario objects.
	 */
	protected $collFormularios;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFormularios.
	 */
	private $lastFormularioCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseTabla object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->mostrar_en_lista = true;
	}

	/**
	 * Get the [id_tabla] column value.
	 * 
	 * @return     int
	 */
	public function getIdTabla()
	{
		return $this->id_tabla;
	}

	/**
	 * Get the [id_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getIdUsuario()
	{
		return $this->id_usuario;
	}

	/**
	 * Get the [id_empresa] column value.
	 * 
	 * @return     int
	 */
	public function getIdEmpresa()
	{
		return $this->id_empresa;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [imagen] column value.
	 * 
	 * @return     string
	 */
	public function getImagen()
	{
		return $this->imagen;
	}

	/**
	 * Get the [mostrar_en_lista] column value.
	 * 
	 * @return     boolean
	 */
	public function getMostrarEnLista()
	{
		return $this->mostrar_en_lista;
	}

	/**
	 * Get the [orden] column value.
	 * 
	 * @return     int
	 */
	public function getOrden()
	{
		return $this->orden;
	}

	/**
	 * Get the [es_ficheros] column value.
	 * 
	 * @return     boolean
	 */
	public function getEsFicheros()
	{
		return $this->es_ficheros;
	}

	/**
	 * Get the [id_categoria] column value.
	 * 
	 * @return     int
	 */
	public function getIdCategoria()
	{
		return $this->id_categoria;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [borrado] column value.
	 * 
	 * @return     boolean
	 */
	public function getBorrado()
	{
		return $this->borrado;
	}

	/**
	 * Set the value of [id_tabla] column.
	 * 
	 * @param      int $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setIdTabla($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tabla !== $v) {
			$this->id_tabla = $v;
			$this->modifiedColumns[] = TablaPeer::ID_TABLA;
		}

		return $this;
	} // setIdTabla()

	/**
	 * Set the value of [id_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setIdUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_usuario !== $v) {
			$this->id_usuario = $v;
			$this->modifiedColumns[] = TablaPeer::ID_USUARIO;
		}

		if ($this->aUsuario !== null && $this->aUsuario->getIdUsuario() !== $v) {
			$this->aUsuario = null;
		}

		return $this;
	} // setIdUsuario()

	/**
	 * Set the value of [id_empresa] column.
	 * 
	 * @param      int $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setIdEmpresa($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_empresa !== $v) {
			$this->id_empresa = $v;
			$this->modifiedColumns[] = TablaPeer::ID_EMPRESA;
		}

		if ($this->aEmpresa !== null && $this->aEmpresa->getIdEmpresa() !== $v) {
			$this->aEmpresa = null;
		}

		return $this;
	} // setIdEmpresa()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = TablaPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [imagen] column.
	 * 
	 * @param      string $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setImagen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->imagen !== $v) {
			$this->imagen = $v;
			$this->modifiedColumns[] = TablaPeer::IMAGEN;
		}

		return $this;
	} // setImagen()

	/**
	 * Set the value of [mostrar_en_lista] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setMostrarEnLista($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->mostrar_en_lista !== $v || $v === true) {
			$this->mostrar_en_lista = $v;
			$this->modifiedColumns[] = TablaPeer::MOSTRAR_EN_LISTA;
		}

		return $this;
	} // setMostrarEnLista()

	/**
	 * Set the value of [orden] column.
	 * 
	 * @param      int $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setOrden($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->orden !== $v) {
			$this->orden = $v;
			$this->modifiedColumns[] = TablaPeer::ORDEN;
		}

		return $this;
	} // setOrden()

	/**
	 * Set the value of [es_ficheros] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setEsFicheros($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->es_ficheros !== $v) {
			$this->es_ficheros = $v;
			$this->modifiedColumns[] = TablaPeer::ES_FICHEROS;
		}

		return $this;
	} // setEsFicheros()

	/**
	 * Set the value of [id_categoria] column.
	 * 
	 * @param      int $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setIdCategoria($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_categoria !== $v) {
			$this->id_categoria = $v;
			$this->modifiedColumns[] = TablaPeer::ID_CATEGORIA;
		}

		if ($this->aParametro !== null && $this->aParametro->getIdParametro() !== $v) {
			$this->aParametro = null;
		}

		return $this;
	} // setIdCategoria()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TablaPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TablaPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [borrado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Tabla The current object (for fluent API support)
	 */
	public function setBorrado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->borrado !== $v) {
			$this->borrado = $v;
			$this->modifiedColumns[] = TablaPeer::BORRADO;
		}

		return $this;
	} // setBorrado()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(TablaPeer::MOSTRAR_EN_LISTA))) {
				return false;
			}

			if ($this->mostrar_en_lista !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_tabla = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_usuario = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->id_empresa = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->nombre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->imagen = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->mostrar_en_lista = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->orden = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->es_ficheros = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->id_categoria = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->created_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->updated_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->borrado = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = TablaPeer::NUM_COLUMNS - TablaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tabla object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsuario !== null && $this->id_usuario !== $this->aUsuario->getIdUsuario()) {
			$this->aUsuario = null;
		}
		if ($this->aEmpresa !== null && $this->id_empresa !== $this->aEmpresa->getIdEmpresa()) {
			$this->aEmpresa = null;
		}
		if ($this->aParametro !== null && $this->id_categoria !== $this->aParametro->getIdParametro()) {
			$this->aParametro = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TablaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TablaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEmpresa = null;
			$this->aUsuario = null;
			$this->aParametro = null;
			$this->collAlcances = null;
			$this->lastAlcanceCriteria = null;

			$this->collRelCampoTablas = null;
			$this->lastRelCampoTablaCriteria = null;

			$this->collFormularios = null;
			$this->lastFormularioCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTabla:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TablaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			TablaPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseTabla:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTabla:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(TablaPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(TablaPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TablaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseTabla:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			TablaPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if ($this->aEmpresa->isModified() || $this->aEmpresa->isNew()) {
					$affectedRows += $this->aEmpresa->save($con);
				}
				$this->setEmpresa($this->aEmpresa);
			}

			if ($this->aUsuario !== null) {
				if ($this->aUsuario->isModified() || $this->aUsuario->isNew()) {
					$affectedRows += $this->aUsuario->save($con);
				}
				$this->setUsuario($this->aUsuario);
			}

			if ($this->aParametro !== null) {
				if ($this->aParametro->isModified() || $this->aParametro->isNew()) {
					$affectedRows += $this->aParametro->save($con);
				}
				$this->setParametro($this->aParametro);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TablaPeer::ID_TABLA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TablaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdTabla($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TablaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAlcances !== null) {
				foreach ($this->collAlcances as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRelCampoTablas !== null) {
				foreach ($this->collRelCampoTablas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFormularios !== null) {
				foreach ($this->collFormularios as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if (!$this->aEmpresa->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmpresa->getValidationFailures());
				}
			}

			if ($this->aUsuario !== null) {
				if (!$this->aUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuario->getValidationFailures());
				}
			}

			if ($this->aParametro !== null) {
				if (!$this->aParametro->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aParametro->getValidationFailures());
				}
			}


			if (($retval = TablaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAlcances !== null) {
					foreach ($this->collAlcances as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRelCampoTablas !== null) {
					foreach ($this->collRelCampoTablas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFormularios !== null) {
					foreach ($this->collFormularios as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TablaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdTabla();
				break;
			case 1:
				return $this->getIdUsuario();
				break;
			case 2:
				return $this->getIdEmpresa();
				break;
			case 3:
				return $this->getNombre();
				break;
			case 4:
				return $this->getImagen();
				break;
			case 5:
				return $this->getMostrarEnLista();
				break;
			case 6:
				return $this->getOrden();
				break;
			case 7:
				return $this->getEsFicheros();
				break;
			case 8:
				return $this->getIdCategoria();
				break;
			case 9:
				return $this->getCreatedAt();
				break;
			case 10:
				return $this->getUpdatedAt();
				break;
			case 11:
				return $this->getBorrado();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TablaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdTabla(),
			$keys[1] => $this->getIdUsuario(),
			$keys[2] => $this->getIdEmpresa(),
			$keys[3] => $this->getNombre(),
			$keys[4] => $this->getImagen(),
			$keys[5] => $this->getMostrarEnLista(),
			$keys[6] => $this->getOrden(),
			$keys[7] => $this->getEsFicheros(),
			$keys[8] => $this->getIdCategoria(),
			$keys[9] => $this->getCreatedAt(),
			$keys[10] => $this->getUpdatedAt(),
			$keys[11] => $this->getBorrado(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TablaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdTabla($value);
				break;
			case 1:
				$this->setIdUsuario($value);
				break;
			case 2:
				$this->setIdEmpresa($value);
				break;
			case 3:
				$this->setNombre($value);
				break;
			case 4:
				$this->setImagen($value);
				break;
			case 5:
				$this->setMostrarEnLista($value);
				break;
			case 6:
				$this->setOrden($value);
				break;
			case 7:
				$this->setEsFicheros($value);
				break;
			case 8:
				$this->setIdCategoria($value);
				break;
			case 9:
				$this->setCreatedAt($value);
				break;
			case 10:
				$this->setUpdatedAt($value);
				break;
			case 11:
				$this->setBorrado($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TablaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdTabla($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdUsuario($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdEmpresa($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNombre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setImagen($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMostrarEnLista($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setOrden($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setEsFicheros($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIdCategoria($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCreatedAt($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUpdatedAt($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setBorrado($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TablaPeer::DATABASE_NAME);

		if ($this->isColumnModified(TablaPeer::ID_TABLA)) $criteria->add(TablaPeer::ID_TABLA, $this->id_tabla);
		if ($this->isColumnModified(TablaPeer::ID_USUARIO)) $criteria->add(TablaPeer::ID_USUARIO, $this->id_usuario);
		if ($this->isColumnModified(TablaPeer::ID_EMPRESA)) $criteria->add(TablaPeer::ID_EMPRESA, $this->id_empresa);
		if ($this->isColumnModified(TablaPeer::NOMBRE)) $criteria->add(TablaPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(TablaPeer::IMAGEN)) $criteria->add(TablaPeer::IMAGEN, $this->imagen);
		if ($this->isColumnModified(TablaPeer::MOSTRAR_EN_LISTA)) $criteria->add(TablaPeer::MOSTRAR_EN_LISTA, $this->mostrar_en_lista);
		if ($this->isColumnModified(TablaPeer::ORDEN)) $criteria->add(TablaPeer::ORDEN, $this->orden);
		if ($this->isColumnModified(TablaPeer::ES_FICHEROS)) $criteria->add(TablaPeer::ES_FICHEROS, $this->es_ficheros);
		if ($this->isColumnModified(TablaPeer::ID_CATEGORIA)) $criteria->add(TablaPeer::ID_CATEGORIA, $this->id_categoria);
		if ($this->isColumnModified(TablaPeer::CREATED_AT)) $criteria->add(TablaPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(TablaPeer::UPDATED_AT)) $criteria->add(TablaPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(TablaPeer::BORRADO)) $criteria->add(TablaPeer::BORRADO, $this->borrado);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TablaPeer::DATABASE_NAME);

		$criteria->add(TablaPeer::ID_TABLA, $this->id_tabla);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdTabla();
	}

	/**
	 * Generic method to set the primary key (id_tabla column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdTabla($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tabla (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdUsuario($this->id_usuario);

		$copyObj->setIdEmpresa($this->id_empresa);

		$copyObj->setNombre($this->nombre);

		$copyObj->setImagen($this->imagen);

		$copyObj->setMostrarEnLista($this->mostrar_en_lista);

		$copyObj->setOrden($this->orden);

		$copyObj->setEsFicheros($this->es_ficheros);

		$copyObj->setIdCategoria($this->id_categoria);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setBorrado($this->borrado);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAlcances() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAlcance($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRelCampoTablas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRelCampoTabla($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFormularios() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFormulario($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdTabla(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tabla Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TablaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TablaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Empresa object.
	 *
	 * @param      Empresa $v
	 * @return     Tabla The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmpresa(Empresa $v = null)
	{
		if ($v === null) {
			$this->setIdEmpresa(NULL);
		} else {
			$this->setIdEmpresa($v->getIdEmpresa());
		}

		$this->aEmpresa = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Empresa object, it will not be re-added.
		if ($v !== null) {
			$v->addTabla($this);
		}

		return $this;
	}


	/**
	 * Get the associated Empresa object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Empresa The associated Empresa object.
	 * @throws     PropelException
	 */
	public function getEmpresa(PropelPDO $con = null)
	{
		if ($this->aEmpresa === null && ($this->id_empresa !== null)) {
			$c = new Criteria(EmpresaPeer::DATABASE_NAME);
			$c->add(EmpresaPeer::ID_EMPRESA, $this->id_empresa);
			$this->aEmpresa = EmpresaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEmpresa->addTablas($this);
			 */
		}
		return $this->aEmpresa;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Tabla The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setIdUsuario(NULL);
		} else {
			$this->setIdUsuario($v->getIdUsuario());
		}

		$this->aUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addTabla($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuario === null && ($this->id_usuario !== null)) {
			$c = new Criteria(UsuarioPeer::DATABASE_NAME);
			$c->add(UsuarioPeer::ID_USUARIO, $this->id_usuario);
			$this->aUsuario = UsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuario->addTablas($this);
			 */
		}
		return $this->aUsuario;
	}

	/**
	 * Declares an association between this object and a Parametro object.
	 *
	 * @param      Parametro $v
	 * @return     Tabla The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setParametro(Parametro $v = null)
	{
		if ($v === null) {
			$this->setIdCategoria(NULL);
		} else {
			$this->setIdCategoria($v->getIdParametro());
		}

		$this->aParametro = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Parametro object, it will not be re-added.
		if ($v !== null) {
			$v->addTabla($this);
		}

		return $this;
	}


	/**
	 * Get the associated Parametro object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Parametro The associated Parametro object.
	 * @throws     PropelException
	 */
	public function getParametro(PropelPDO $con = null)
	{
		if ($this->aParametro === null && ($this->id_categoria !== null)) {
			$c = new Criteria(ParametroPeer::DATABASE_NAME);
			$c->add(ParametroPeer::ID_PARAMETRO, $this->id_categoria);
			$this->aParametro = ParametroPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aParametro->addTablas($this);
			 */
		}
		return $this->aParametro;
	}

	/**
	 * Clears out the collAlcances collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAlcances()
	 */
	public function clearAlcances()
	{
		$this->collAlcances = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAlcances collection (array).
	 *
	 * By default this just sets the collAlcances collection to an empty array (like clearcollAlcances());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAlcances()
	{
		$this->collAlcances = array();
	}

	/**
	 * Gets an array of Alcance objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tabla has previously been saved, it will retrieve
	 * related Alcances from storage. If this Tabla is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Alcance[]
	 * @throws     PropelException
	 */
	public function getAlcances($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAlcances === null) {
			if ($this->isNew()) {
			   $this->collAlcances = array();
			} else {

				$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

				AlcancePeer::addSelectColumns($criteria);
				$this->collAlcances = AlcancePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

				AlcancePeer::addSelectColumns($criteria);
				if (!isset($this->lastAlcanceCriteria) || !$this->lastAlcanceCriteria->equals($criteria)) {
					$this->collAlcances = AlcancePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAlcanceCriteria = $criteria;
		return $this->collAlcances;
	}

	/**
	 * Returns the number of related Alcance objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Alcance objects.
	 * @throws     PropelException
	 */
	public function countAlcances(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAlcances === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

				$count = AlcancePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

				if (!isset($this->lastAlcanceCriteria) || !$this->lastAlcanceCriteria->equals($criteria)) {
					$count = AlcancePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAlcances);
				}
			} else {
				$count = count($this->collAlcances);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Alcance object to this object
	 * through the Alcance foreign key attribute.
	 *
	 * @param      Alcance $l Alcance
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAlcance(Alcance $l)
	{
		if ($this->collAlcances === null) {
			$this->initAlcances();
		}
		if (!in_array($l, $this->collAlcances, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAlcances, $l);
			$l->setTabla($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tabla is new, it will return
	 * an empty collection; or if this Tabla has previously
	 * been saved, it will retrieve related Alcances from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tabla.
	 */
	public function getAlcancesJoinEmpresa($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAlcances === null) {
			if ($this->isNew()) {
				$this->collAlcances = array();
			} else {

				$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

				$this->collAlcances = AlcancePeer::doSelectJoinEmpresa($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

			if (!isset($this->lastAlcanceCriteria) || !$this->lastAlcanceCriteria->equals($criteria)) {
				$this->collAlcances = AlcancePeer::doSelectJoinEmpresa($criteria, $con, $join_behavior);
			}
		}
		$this->lastAlcanceCriteria = $criteria;

		return $this->collAlcances;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tabla is new, it will return
	 * an empty collection; or if this Tabla has previously
	 * been saved, it will retrieve related Alcances from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tabla.
	 */
	public function getAlcancesJoinUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAlcances === null) {
			if ($this->isNew()) {
				$this->collAlcances = array();
			} else {

				$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

				$this->collAlcances = AlcancePeer::doSelectJoinUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AlcancePeer::ID_TABLA, $this->id_tabla);

			if (!isset($this->lastAlcanceCriteria) || !$this->lastAlcanceCriteria->equals($criteria)) {
				$this->collAlcances = AlcancePeer::doSelectJoinUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastAlcanceCriteria = $criteria;

		return $this->collAlcances;
	}

	/**
	 * Clears out the collRelCampoTablas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRelCampoTablas()
	 */
	public function clearRelCampoTablas()
	{
		$this->collRelCampoTablas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRelCampoTablas collection (array).
	 *
	 * By default this just sets the collRelCampoTablas collection to an empty array (like clearcollRelCampoTablas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRelCampoTablas()
	{
		$this->collRelCampoTablas = array();
	}

	/**
	 * Gets an array of RelCampoTabla objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tabla has previously been saved, it will retrieve
	 * related RelCampoTablas from storage. If this Tabla is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RelCampoTabla[]
	 * @throws     PropelException
	 */
	public function getRelCampoTablas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRelCampoTablas === null) {
			if ($this->isNew()) {
			   $this->collRelCampoTablas = array();
			} else {

				$criteria->add(RelCampoTablaPeer::ID_TABLA, $this->id_tabla);

				RelCampoTablaPeer::addSelectColumns($criteria);
				$this->collRelCampoTablas = RelCampoTablaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RelCampoTablaPeer::ID_TABLA, $this->id_tabla);

				RelCampoTablaPeer::addSelectColumns($criteria);
				if (!isset($this->lastRelCampoTablaCriteria) || !$this->lastRelCampoTablaCriteria->equals($criteria)) {
					$this->collRelCampoTablas = RelCampoTablaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRelCampoTablaCriteria = $criteria;
		return $this->collRelCampoTablas;
	}

	/**
	 * Returns the number of related RelCampoTabla objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RelCampoTabla objects.
	 * @throws     PropelException
	 */
	public function countRelCampoTablas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRelCampoTablas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RelCampoTablaPeer::ID_TABLA, $this->id_tabla);

				$count = RelCampoTablaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RelCampoTablaPeer::ID_TABLA, $this->id_tabla);

				if (!isset($this->lastRelCampoTablaCriteria) || !$this->lastRelCampoTablaCriteria->equals($criteria)) {
					$count = RelCampoTablaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRelCampoTablas);
				}
			} else {
				$count = count($this->collRelCampoTablas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a RelCampoTabla object to this object
	 * through the RelCampoTabla foreign key attribute.
	 *
	 * @param      RelCampoTabla $l RelCampoTabla
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRelCampoTabla(RelCampoTabla $l)
	{
		if ($this->collRelCampoTablas === null) {
			$this->initRelCampoTablas();
		}
		if (!in_array($l, $this->collRelCampoTablas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRelCampoTablas, $l);
			$l->setTabla($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tabla is new, it will return
	 * an empty collection; or if this Tabla has previously
	 * been saved, it will retrieve related RelCampoTablas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tabla.
	 */
	public function getRelCampoTablasJoinCampo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRelCampoTablas === null) {
			if ($this->isNew()) {
				$this->collRelCampoTablas = array();
			} else {

				$criteria->add(RelCampoTablaPeer::ID_TABLA, $this->id_tabla);

				$this->collRelCampoTablas = RelCampoTablaPeer::doSelectJoinCampo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RelCampoTablaPeer::ID_TABLA, $this->id_tabla);

			if (!isset($this->lastRelCampoTablaCriteria) || !$this->lastRelCampoTablaCriteria->equals($criteria)) {
				$this->collRelCampoTablas = RelCampoTablaPeer::doSelectJoinCampo($criteria, $con, $join_behavior);
			}
		}
		$this->lastRelCampoTablaCriteria = $criteria;

		return $this->collRelCampoTablas;
	}

	/**
	 * Clears out the collFormularios collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFormularios()
	 */
	public function clearFormularios()
	{
		$this->collFormularios = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFormularios collection (array).
	 *
	 * By default this just sets the collFormularios collection to an empty array (like clearcollFormularios());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFormularios()
	{
		$this->collFormularios = array();
	}

	/**
	 * Gets an array of Formulario objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tabla has previously been saved, it will retrieve
	 * related Formularios from storage. If this Tabla is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Formulario[]
	 * @throws     PropelException
	 */
	public function getFormularios($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFormularios === null) {
			if ($this->isNew()) {
			   $this->collFormularios = array();
			} else {

				$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

				FormularioPeer::addSelectColumns($criteria);
				$this->collFormularios = FormularioPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

				FormularioPeer::addSelectColumns($criteria);
				if (!isset($this->lastFormularioCriteria) || !$this->lastFormularioCriteria->equals($criteria)) {
					$this->collFormularios = FormularioPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFormularioCriteria = $criteria;
		return $this->collFormularios;
	}

	/**
	 * Returns the number of related Formulario objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Formulario objects.
	 * @throws     PropelException
	 */
	public function countFormularios(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFormularios === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

				$count = FormularioPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

				if (!isset($this->lastFormularioCriteria) || !$this->lastFormularioCriteria->equals($criteria)) {
					$count = FormularioPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFormularios);
				}
			} else {
				$count = count($this->collFormularios);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Formulario object to this object
	 * through the Formulario foreign key attribute.
	 *
	 * @param      Formulario $l Formulario
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFormulario(Formulario $l)
	{
		if ($this->collFormularios === null) {
			$this->initFormularios();
		}
		if (!in_array($l, $this->collFormularios, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFormularios, $l);
			$l->setTabla($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tabla is new, it will return
	 * an empty collection; or if this Tabla has previously
	 * been saved, it will retrieve related Formularios from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tabla.
	 */
	public function getFormulariosJoinUsuarioRelatedByIdUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFormularios === null) {
			if ($this->isNew()) {
				$this->collFormularios = array();
			} else {

				$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

				$this->collFormularios = FormularioPeer::doSelectJoinUsuarioRelatedByIdUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

			if (!isset($this->lastFormularioCriteria) || !$this->lastFormularioCriteria->equals($criteria)) {
				$this->collFormularios = FormularioPeer::doSelectJoinUsuarioRelatedByIdUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastFormularioCriteria = $criteria;

		return $this->collFormularios;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tabla is new, it will return
	 * an empty collection; or if this Tabla has previously
	 * been saved, it will retrieve related Formularios from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tabla.
	 */
	public function getFormulariosJoinUsuarioRelatedByIdUsuarioCreador($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TablaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFormularios === null) {
			if ($this->isNew()) {
				$this->collFormularios = array();
			} else {

				$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

				$this->collFormularios = FormularioPeer::doSelectJoinUsuarioRelatedByIdUsuarioCreador($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FormularioPeer::ID_TABLA, $this->id_tabla);

			if (!isset($this->lastFormularioCriteria) || !$this->lastFormularioCriteria->equals($criteria)) {
				$this->collFormularios = FormularioPeer::doSelectJoinUsuarioRelatedByIdUsuarioCreador($criteria, $con, $join_behavior);
			}
		}
		$this->lastFormularioCriteria = $criteria;

		return $this->collFormularios;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAlcances) {
				foreach ((array) $this->collAlcances as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRelCampoTablas) {
				foreach ((array) $this->collRelCampoTablas as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFormularios) {
				foreach ((array) $this->collFormularios as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAlcances = null;
		$this->collRelCampoTablas = null;
		$this->collFormularios = null;
			$this->aEmpresa = null;
			$this->aUsuario = null;
			$this->aParametro = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseTabla:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseTabla::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseTabla
