<?php
// auto-generated by sfPropelAdmin
// date: 2008/09/05 11:44:53
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('sfTransUnit/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_source"><?php echo __($labels['trans_unit{source}']) ?></label>
    <div class="content">
    <?php echo input_tag('filters[source]', isset($filters['source']) ? $filters['source'] : null, array (
  'size' => '15',
  'disabled' => false,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_translated"><?php echo __($labels['trans_unit{translated}']) ?></label>
    <div class="content">
    <?php echo get_partial('translated', array('type' => 'filter', 'filters' => $filters)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_catfilter"><?php echo __($labels['trans_unit{catfilter}']) ?></label>
    <div class="content">
    <?php echo get_partial('catfilter', array('type' => 'filter', 'filters' => $filters)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'sfTransUnit/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
