<?php
// auto-generated by sfPropelAdmin
// date: 2008/09/05 11:44:53
?>
<td colspan="5">
    <?php echo get_partial('lang', array('type' => 'list', 'trans_unit' => $trans_unit)) ?>
     - 
    <?php echo link_to($trans_unit->getSource() ? $trans_unit->getSource() : '-', 'sfTransUnit/edit?msg_id='.$trans_unit->getMsgId()) ?>
     - 
    <?php echo $trans_unit->getTarget() ?>
     - 
    <?php echo $trans_unit->getComments() ?>
     - 
    <?php echo $trans_unit->getTranslated() ?>
     - 
</td>