dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      datasource: legedia
      classname: PropelPDO
      dsn:        mysql:dbname=legedia;host=localhost
      username:   legedia
      password:   pass_legedia
      encoding:   utf8
      persistent: true
      pooling:    true