<?php
// auto-generated by sfPropelAdmin
// date: 2008/09/05 11:44:50
?>
<td colspan="8">
    <?php echo link_to($catalogue->getCatId() ? $catalogue->getCatId() : '-', 'sfCatalogue/edit?cat_id='.$catalogue->getCatId()) ?>
     - 
    <?php echo $catalogue->getNvisible() ?>
     - 
    <?php echo $catalogue->getName() ?>
     - 
    <?php echo $catalogue->getSourceLang() ?>
     - 
    <?php echo $catalogue->getTargetLang() ?>
     - 
    <?php echo ($catalogue->getDateCreated() !== null && $catalogue->getDateCreated() !== '') ? format_date($catalogue->getDateCreated(), "f") : '' ?>
     - 
    <?php echo ($catalogue->getDateModified() !== null && $catalogue->getDateModified() !== '') ? format_date($catalogue->getDateModified(), "f") : '' ?>
     - 
    <?php echo $catalogue->getAuthor() ?>
     - 
</td>