<?php
// auto-generated by sfAdvancedAdmin
// date: 2008/01/10 11:37:49
?>
  <th id="sf_admin_list_th_id_sesion">
        <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/sesion/sort') == 'id_sesion'): ?>
      <?php echo link_to(__($labels['sesion{sesion}']), 'sesiones/list?sort=id_sesion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__($labels['sesion{sesion}']), 'sesiones/list?sort=id_sesion&type=asc') ?>
      <?php endif; ?>
   
          </th>
  <th id="sf_admin_list_th_id_usuario">

        <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/sesion/sort') == 'id_usuario'): ?>
      <?php echo link_to(__($labels['sesion{idusuario}']), 'sesiones/list?sort=id_usuario&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__($labels['sesion{idusuario}']), 'sesiones/list?sort=id_usuario&type=asc') ?>
      <?php endif; ?>
          </th>
          <!--
  <th id="sf_admin_list_th_sesion">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/sesion/sort') == 'sesion'): ?>
      <?php echo link_to(__('Sesion'), 'sesiones/list?sort=sesion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Sesion'), 'sesiones/list?sort=sesion&type=asc') ?>
      <?php endif; ?>
          </th>
          -->
   <th>
		<?php echo __($labels['sesion{desde}']) ?>	   
   </th>
    <th>
		<?php echo __($labels['sesion{hasta}']) ?>	   
   </th>
  <th id="sf_admin_list_th_ip">
         <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/sesion/sort') == 'IP'): ?>
      <?php echo link_to(__($labels['sesion{ip}']), 'sesiones/list?sort=IP&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/sesion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__($labels['sesion{ip}']), 'sesiones/list?sort=IP&type=asc') ?>
      <?php endif; ?>
          </th>
  <th><?php echo __($labels['sesion{acciones}']) ?></th>
