<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/31 13:28:14
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('usuarios/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_id_usuario"><?php echo __('Id usuario:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[id_usuario]', isset($filters['id_usuario']) ? $filters['id_usuario'] : null, array (
  'size' => 7,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_usuario"><?php echo __('Usuario:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[usuario]', isset($filters['usuario']) ? $filters['usuario'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_apellido1"><?php echo __('Primer apellido:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[apellido1]', isset($filters['apellido1']) ? $filters['apellido1'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_email"><?php echo __('Email:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[email]', isset($filters['email']) ? $filters['email'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_updated_at"><?php echo __('Última visita:') ?></label>
    <div class="content">
    <?php echo input_date_range_tag('filters[updated_at]', isset($filters['updated_at']) ? $filters['updated_at'] : null, array (
  'rich' => true,
  'withtime' => false,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'usuarios/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>

