<?php
// auto-generated by sfPropelAdmin
// date: 2008/07/16 18:56:31
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('create'), 'encargados/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
