<?php
// auto-generated by sfPropelAdmin
// date: 2007/08/30 11:31:00
?>
<td colspan="2">
    <?php echo link_to($familia->getIdFamilia() ? $familia->getIdFamilia() : __('-'), 'familias/edit?id_familia='.$familia->getIdFamilia()) ?>
     - 
    <?php echo $familia->getNombre() ?>
     - 
</td>