<?php


/**
 * This class adds structure of 'documentos' table to 'legedia' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Oct 27 21:17:37 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DocumentoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DocumentoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(DocumentoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(DocumentoPeer::TABLE_NAME);
		$tMap->setPhpName('Documento');
		$tMap->setClassname('Documento');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID_DOCUMENTO', 'IdDocumento', 'INTEGER', true, null);

		$tMap->addForeignKey('ID_EMPRESA', 'IdEmpresa', 'INTEGER', 'empresa', 'ID_EMPRESA', false, null);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 250);

		$tMap->addForeignKey('ID_ITEM', 'IdItem', 'INTEGER', 'item', 'ID_ITEM', false, null);

	} // doBuild()

} // DocumentoMapBuilder
