<?php


/**
 * This class adds structure of 'parametro' table to 'legedia' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Oct 27 21:17:36 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ParametroMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ParametroMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ParametroPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ParametroPeer::TABLE_NAME);
		$tMap->setPhpName('Parametro');
		$tMap->setClassname('Parametro');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID_PARAMETRO', 'IdParametro', 'INTEGER', true, null);

		$tMap->addForeignKey('TIPOPARAMETRO', 'Tipoparametro', 'VARCHAR', 'parametro_def', 'TIPOPARAMETRO', true, 100);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 100);

		$tMap->addColumn('ORDEN', 'Orden', 'INTEGER', false, null);

		$tMap->addColumn('NUMERO', 'Numero', 'FLOAT', false, null);

		$tMap->addColumn('NUMERO2', 'Numero2', 'FLOAT', false, null);

		$tMap->addColumn('CADENA', 'Cadena', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CADENA1', 'Cadena1', 'LONGVARCHAR', false, null);

		$tMap->addColumn('OTROOBJETO', 'Otroobjeto', 'INTEGER', false, null);

		$tMap->addColumn('SI_NO', 'SiNo', 'BOOLEAN', false, null);

		$tMap->addColumn('FECHA', 'Fecha', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('FECHABORRADO', 'Fechaborrado', 'TIMESTAMP', false, null);

		$tMap->addColumn('NOMBREFICHERO', 'Nombrefichero', 'VARCHAR', false, 200);

		$tMap->addColumn('TIPO', 'Tipo', 'VARCHAR', false, 100);

		$tMap->addColumn('FICHERO', 'Fichero', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TAMANO', 'Tamano', 'INTEGER', false, null);

	} // doBuild()

} // ParametroMapBuilder
