<?php
// auto-generated by sfPropelAdmin
// date: 2008/09/05 11:44:50
?>
    <td><?php echo link_to($catalogue->getCatId() ? $catalogue->getCatId() : '-', 'sfCatalogue/edit?cat_id='.$catalogue->getCatId()) ?></td>
    <td><?php echo $catalogue->getNvisible() ?></td>
      <td><?php echo $catalogue->getName() ?></td>
      <td><?php echo $catalogue->getSourceLang() ?></td>
      <td><?php echo $catalogue->getTargetLang() ?></td>
    <!--  <?php /* Ana: 16-02-09 No se necesita esta información
      <td><?php echo ($catalogue->getDateCreated() !== null && $catalogue->getDateCreated() !== '') ? format_date($catalogue->getDateCreated(), "f") : '' ?></td>
      <td><?php echo ($catalogue->getDateModified() !== null && $catalogue->getDateModified() !== '') ? format_date($catalogue->getDateModified(), "f") : '' ?></td>
      
      <td><?php echo $catalogue->getAuthor() ?></td>
*/ ?> -->  