<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/02 10:56:45
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'documentos/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
