<?php
// auto-generated by sfPropelAdmin
// date: 2008/09/05 11:44:53
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edit Translation', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('sfTransUnit/edit_header', array('trans_unit' => $trans_unit)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('sfTransUnit/edit_messages', array('trans_unit' => $trans_unit, 'labels' => $labels)) ?>
<?php include_partial('sfTransUnit/edit_form', array('trans_unit' => $trans_unit, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('sfTransUnit/edit_footer', array('trans_unit' => $trans_unit)) ?>
</div>

</div>
